### ISSUE TITLE
Add setting to maxCycles for no max.

### ISSUE THREAD

**Issue by nbunney** [nbunney/jQueryFullscreenCycler#3]
Add code that will allow maxCycles option to cycler forever.  I am going to suggest the value of 0.

**Comment by daviesgeek** [comment]
Ok. How about if nothing is passed, it isn't set?

**Comment by nbunney** [comment]
Well, we should set a default in our code, nothing passed would pull this value.  But the user should be able to pass every option explicitly.  So set the default to 0.

**Comment by daviesgeek** [comment]
Got it.
