### ISSUE TITLE
Add side sliding transition with jqueryUI transitions if available.

### ISSUE THREAD

**Issue by nbunney** [nbunney/jQueryFullscreenCycler#5]

**Comment by daviesgeek** [comment]
Do you have to have a dependency on jQuery UI?

**Comment by nbunney** [comment]
No, but we can check and see if it is loaded and if it is we can use the
transitions.

**Comment by daviesgeek** [comment]
Ah, ok got it.

On Friday, February 7, 2014, Nathan Bunney notifications@github.com wrote:

> No, but we can check and see if it is loaded and if it is we can use the
> transitions.
> 
> Nathan Bunney
> 209-765-1262
> 
> On Fri, Feb 7, 2014 at 12:33 PM, Matthew Davies <notifications@github.com<javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> 
> > wrote:
> > 
> > Do you have to have a dependency on jQuery UI?
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub<
> > https://github.com/nbunney/jQueryFullscreenCycler/issues/5#issuecomment-34499294
> > 
> > .
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/nbunney/jQueryFullscreenCycler/issues/5#issuecomment-34504913
> .

## 

Matthew Davies
Developer at Inventaweb.net
Co-Founder of OffBlock Films http://offblockfilms.com
Find me on my blog. http://thegeektechblog.blogspot.com

**Comment by daviesgeek** [comment]
Addressed by #6
