### ISSUE TITLE
Change size in README

### ISSUE THREAD

**Issue by daviesgeek** [nbunney/jQueryFullscreenCycler#7]
According to the README, jQueryFullscreenCycler is "Only 4K minified". However, I just checked on my local box, and the minified version is 2.1K. Is that just me or is it smaller than the advertised 4K?

![screen shot 2014-02-09 at 2 21 33 pm](https://f.cloud.github.com/assets/2348508/2121209/a5d6fafc-91d8-11e3-8561-685126df4e61.png)
![screen shot 2014-02-09 at 2 21 58 pm](https://f.cloud.github.com/assets/2348508/2121210/a7f90974-91d8-11e3-84f6-9842eb5c3c58.png)

**Comment by nbunney** [comment]
Just edited the file to say under 3K.  Would rather be a little conservative here.  3K is still tiny so I think we are good.
